apiVersion: v1
kind: Secret
metadata:
  name: neon-db-secret
  namespace: todo-app
type: Opaque
data:
  database_url: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpuUEdfYnJlOHRJV1R5SjNTQGVwLXlvdW5nLXF1ZWVuLWFkMmgxNHRyLXBvb2xlci5jLTIudXMtZWFzdC0xLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbG1vZGU9cmVxdWlyZSZjaGFubmVsX2JpbmRpbmc9cmVxdWlyZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: todo-app
type: Opaque
data:
  api_key: eW91cl9vcGVuaV9hcGlfa2V5X2hlcmU=